
version: '3.7'
services:
  dashboard_api:
    hostname: dashboard-api
    build:
      context: ./dashboard-api
      dockerfile: Dockerfile
    environment:
      - RAILS_ENV=development
    volumes:
      - ./dashboard-api:/app
    networks:
      - soa_network
    command: bundle exec rails server -p 8000 -b 0.0.0.0
  user_service:
    hostname: user-service
    build:
      context: ./user-service
      dockerfile: Dockerfile
    environment:
      - RAILS_ENV=development
    volumes:
      - ./user-service:/app
    networks:
      - soa_network
    command: bundle exec rails server -p 8000 -b 0.0.0.0
  calendar_service:
    hostname: calendar-service
    build:
      context: ./calendar-service
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - ./calendar-service:/app
    networks:
      - soa_network
    command: npm start
  billing_service:
    hostname: billing-service
    build:
      context: ./billing-service
      dockerfile: Dockerfile
    volumes:
      - ./billing-service:/app
    networks:
      - soa_network    
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:8000
    networks:
      - soa_network
    depends_on:
      - dashboard_api
      - billing_service
      - user_service
      - calendar_service

networks:
  soa_network:
    driver: bridge
